### PR TITLE
fix typescript declaration for app.use with async functions

### PR DESCRIPTION
**Pull request by tellnes**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
   - `npm run benchmark` fails with `missing script: benchmark`
- [x] tests and/or benchmarks are included
     - not relevant
- [x] documentation is changed or added
    - not relevant
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Btw, the test fails with an `listen EADDRINUSE: address already in use :::3000` if there is something else listening on port `3000` where the tests is run.

### CODE REVIEW

**Comment by climba03003** [comment]
I think it really doesn't matter to the return value to be `void` or `Promise<void>`
It is valid for `void` itself only.
image

**Comment by tellnes** [comment]
It does matter if you are running linting with the [@typescript-eslint/no-misused-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md) rule enabled.

But I think it should be `unknown` instead of `void`. That will allow you to use promises which returns something also. That will be fine since avvio seems to ignores any return value. I will update the PR.

**Comment by tellnes** [comment]
PR updated. Changed return value from `void | Promise<void>` to `unknown | Promise<unknown>`

**Review by mcollina — CHANGES_REQUESTED** [review]
Would you mind to add a test in https://github.com/fastify/avvio/tree/master/test/types for this?

**Comment by tellnes** [comment]
@mcollina Since this is to fix a linting rule, I don't think I will be able to add a failing test case without configuring eslint for this project.

**Comment by tellnes** [comment]
Test case added. I did also remove `Promise<unknown>`. That is not needed anymore after I also changed the non-async part from `void` to `unknown` in an earlier change. The change is now just to change it from `void` to `unknown`.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
