### PR TITLE
Feat/updates for v5

### LINKED ISSUE #245: Updating for v5
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I'm looking to update this repo for v5. https://github.com/fastify/fastify/issues/5116

Changes Needed (Please let me know if anything might be missing)

- Update workflows to use v4
- Update dependencies

### PR DESCRIPTION
**Pull request by nrayburn-tech**
Fixes #245.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by nrayburn-tech** [comment]
- [ ]  Update workflow to use v4 tag.

**Comment by jsumners** [comment]
The `next` branch on this repo is several months old and was last updated by @Uzlopak. We really need to be coordinating with the "I'm interested in working on this" issue prior to starting pull requests so that we know we have a valid branch to target. As it is, I have created https://github.com/fastify/avvio/tree/next-fastify-v5 for now and rebased this PR. Some coordination needs to happed to determine if this is appropriate or if changes in the current `next` branch need to be incorporated.

Also, a word of warning: this is a complicated module. We are likely going to want @mcollina's input on this one.

**Comment by nrayburn-tech** [comment]
This PR now contains the updates I'm aware of being needed from https://github.com/fastify/fastify/issues/5116.  If something additional needs to happen (as either this PR or a separate one) we can discuss it either here or in https://github.com/fastify/avvio/issues/245.

**Comment by gurgunday** [comment]
I think we can combine them in `next`

If I understand correctly, @Uzlopak just removed `express`; there is no big change underway

**Review by gurgunday — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
