### PR TITLE
extract noop

### PR DESCRIPTION
**Pull request by Uzlopak**
based on #199 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — COMMENTED** [review]
Do we need this optimization? 😅

**Comment by Uzlopak** [comment]
just reordering stuff.

**Review by mcollina — CHANGES_REQUESTED** [review]
It's actually better not to do this from a perf perspective. V8 optimizes noop in the same file better (or used to).

**Comment by Uzlopak** [comment]
Ok ;)

**Pull request closed without merging**
