### PR TITLE
Improve plugin getName() speed

### PR DESCRIPTION
**Pull request by airhorns**
While profiling some slow tests and slow boot times for my application, I noticed `avvio`'s plugin naming stuff at the top of the profile for the first test case executed. I have a lot of fastify plugins (say 500 or so), and I think getting the name for all of them starts to get a bit slow because it is O(n^2). This switches the plugin naming to use a prebuilt cache of names with a WeakMap instead of iterating require.cache every time.

Here's the benchmark I used:

```javascript
const Benchmark = require('benchmark')
const plugin = require('./plugin')
const glob = require('glob')
const modules = glob.sync('./node_modules/*/')

console.log(`Benchmarking against ${modules.length} modules`)
const suite = new Benchmark.Suite()

suite.add('getName()', function () {
  for (const module of modules) {
    plugin.getName(module)
  }
})
  .on('cycle', function (event) {
    console.log(String(event.target))
  })
  .run()
```

On `master`:

```
inspector ~/C/avvio (master*) ➜  node name-bench.js
Benchmarking against 392 modules
getName() x 1,818 ops/sec ±1.68% (90 runs sampled)
```

On `faster-plugin-naming`:

```
inspector ~/C/avvio (faster-plugin-naming*) ➜  node name-bench.js
Benchmarking against 392 modules
getName() x 8,217 ops/sec ±0.51% (89 runs sampled)
```

Note if you want to run the benchmark yourself you'll have to `npm install benchmark` and export the `getName` function from the `plugin` module. 

I am not aware of a way to do this without using the deprecated `require.extensions` property in node, but, iterating the require cache every time a plugin is named seems excessive so it is justified to me. Happy to hear your feedback though.

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Are you loading your plugins with `fastify-autoload`? In case we should make sure you never hit this method.

I'm not fond of the current code and the fact that it would only work for commonjs and not esm. I think we should think of  refactoring this by drastically changing the algorithm. _I think we should eventually drop it_.

A slightly worse solution that do not use the deprecated API is computing a `WeakMap` of all the modules on first call of `getName()` (and then every time there is a miss).

**Comment by airhorns** [comment]
> Are you loading your plugins with fastify-autoload?

No, I'm using my own loader thing because I needed more control over load order and encapsulation than fastify-autoload had available

> I'm not fond of the current code and the fact that it would only work for commonjs and not esm. I think we should think of refactoring this by drastically changing the algorithm. I think we should eventually drop it.

Same, not ideal. We could use just `function.name` if it exists and the function text otherwise?

> A slightly worse solution that do not use the deprecated API is computing a WeakMap of all the modules on first call of getName() (and then every time there is a miss).

That would work, but I think there will still be a lot of misses because by definition this code is getting run during code loading, which means the require cache is not going to be full yet.

**Comment by mcollina** [comment]
You should do https://github.com/fastify/fastify-autoload/blob/d0d93a542c38aba4ce281bf3e61304d2cc8efed0/index.js#L252. I think fastify-autoload manage this automatically without triggering the problem.

**Comment by airhorns** [comment]
I can do that, but, other plugins aren't always going to register themselves with a name, do we really want to leave this O(N^2) traversal in here?

**Comment by mcollina** [comment]
This is there as last-measure scenario. The only way to provide a good user experience is with the auto-loading libraries setting those metadata properly.

I'm happy to remove it, but we should update the docs somewhere in FAstify clarifying that they should specify the name somehow.

**Comment by airhorns** [comment]
Ok, I will close and open a docs PR at some point.

**Comment by airhorns** [comment]
This came up again in another profiling session for me locally and I noticed something I missed before. As far as I can tell, we always call the `getName` function on any functions passed to avvio plugins: https://github.com/fastify/avvio/blob/master/plugin.js#L50 . So, even if a fastify plugin specifies a name in the fastify plugin opts, avvio still figures out its own name in the constructor using this slow function. Is there a `opts.name || getName(func)` bit missing? Or am I missing something in one of the downstream packages?

**Comment by mcollina** [comment]
That would be a good optimization! Could you check it this would work?

**Pull request closed without merging**
