### PR TITLE
feat: implement error factory

### PR DESCRIPTION
**Pull request by MetCoder95**
Implements [Fastify#2842](https://github.com/fastify/fastify/issues/2842)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I think this should be semver-major.

**Comment by MetCoder95** [comment]
Done, for some reason it says is up-to-date but marks all those commits out of nowhere

**Comment by mcollina** [comment]
`next` did not have all the commits

**Comment by mcollina** [comment]
Can you push again? I'm sorry

**Comment by MetCoder95** [comment]
Done! Thanks 👍

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
